services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER:-pollpulse_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pollpulse_password}
      POSTGRES_DB: ${DB_NAME:-pollpulse_db}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-pollpulse_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: adminer
    networks:
      - app-network
    restart: always
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    ports:
      - "8081:8080"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: "${DOCKER_IMAGE?Variable not set}:${TAG:-latest}"
    restart: always
    volumes:
      - .:/app:cached
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file:
      - .env
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DB_NAME: ${DB_NAME:-pollpulse_db}
      DB_USER: ${DB_USER:-pollpulse_user}
      DB_PASSWORD: ${DB_PASSWORD:-pollpulse_password}
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
