# Generated by Django 5.1.6 on 2025-03-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_type',
            field=models.CharField(default='single_choice', max_length=50),
        ),
        migrations.AddField(
            model_name='poll',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
