name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy environment variables
        run: cp .env.example .env
        
      - name: Build and start containers
        run: docker compose up -d --build

      - name: Wait for services to be ready
        run: sleep 20

      - name: Tear down containers
        if: always()
        run: docker compose down
