name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy environment variables
        run: cp .env.example .env 
        
      - name: Build and start containers
        run: docker compose --env-file .env up -d --build

      - name: Wait for services to be ready
        run: sleep 20

      - name: Tear down containers
        if: always()
        run: docker compose down
